# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

boolean是布尔型数据
float是浮点型数据
int是整数型数据

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [1]:
j = 1
sum = 0
for i in range(1,100):
    sum+= j*i
    j = j*(-1)
print(sum)

50


1.3  将字符串 s="yoyo" 转换成列表

In [2]:
string = 'yoyo'
print(list(string))

['y', 'o', 'y', 'o']


# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

在1到99之间，从索引号为2即3开始，每个3个数取数，得到到序列取最后10个数输出

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [3]:
class stock:
    def __init__(self,stockname,high,close):
        self.stockname = stockname
        self.high = high
        self.close = close
    def cal(self):
        return {self.stockname+'_dif':self.high-self.close}
stock1 = stock('one',15,7)
print(stock1.cal())
stock2 = stock('two',66,20)
print(stock2.cal())

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

查看列名：DataFrame.cloumns
数据转置：transpose()

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [4]:
import pandas as pd
import numpy as np
import talib as ta
stock = pd.read_excel('D://sz50.xlsx',sheet_name='600029.XSHG',index_col='datetime')
close = np.array(stock.close)
data = ta.EMA(close,timeperiod=10)
print(data[-5:])

[118.50976634 118.43889974 118.02455433 118.34918081 118.7347843 ]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [5]:
import pandas as pd
symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('D://sz50.xlsx',sheet_name=s, index_col='datetime')
    data_dict[s] = data.loc[:]
PN = pd.Panel(data_dict)
print(PN)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume


3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [6]:
stock_numpy = np.array(PN)
print(stock_numpy.shape)
print(stock_numpy[:,-20:,0])

(3, 215, 5)
[[120.56 120.94 120.19 120.47 119.06 118.22 117.56 117.47 117.94 116.91
  117.56 117.94 117.66 118.41 120.   118.12 118.12 116.16 119.81 120.47]
 [120.56 120.94 120.19 120.47 119.06 118.22 117.56 117.47 117.94 116.91
  117.56 117.94 117.66 118.41 120.   118.12 118.12 116.16 119.81 120.47]
 [120.56 120.94 120.19 120.47 119.06 118.22 117.56 117.47 117.94 116.91
  117.56 117.94 117.66 118.41 120.   118.12 118.12 116.16 119.81 120.47]]


3.5 建立一个5*5的矩阵，值从0到24

In [7]:
import numpy as np
print(np.arange(25).reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
